# Generated by Django 5.2.12 on 2026-03-08 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_remove_tender_is_active_application_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='notifications_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('customer', 'Customer'), ('supplier', 'Supplier'), ('both', 'Both'), ('admin', 'Admin')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('customer', 'Хочу создавать тендеры'), ('supplier', 'Хочу участвовать в тендерах'), ('both', 'Хочу и создавать тендеры, и участвовать')], max_length=20)),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_type', models.CharField(blank=True, max_length=255)),
                ('activity_description', models.TextField()),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_person', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
