# Generated by Django 5.2.12 on 2026-03-08 18:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_tender_notifications_sent_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('winner', 'Winner'), ('lost', 'Lost'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('admin', 'Admin')], default='supplier', max_length=20),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='request_type',
            field=models.CharField(choices=[('customer', 'Хочу создавать тендеры'), ('supplier', 'Хочу участвовать в тендерах')], max_length=20),
        ),
    ]
